# Generated by Django 5.2.1 on 2025-06-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Doctor',
        ),
    ]
