# Generated by Django 5.2.1 on 2025-06-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='User',
        ),
    ]
