# Generated by Django 5.2.1 on 2025-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('demail', models.EmailField(max_length=254)),
                ('dmobile', models.BigIntegerField()),
                ('dpassword', models.CharField(max_length=20)),
                ('dexperience', models.CharField(max_length=50)),
            ],
        ),
    ]
