# Generated by Django 5.2.1 on 2025-06-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='dpassword',
        ),
    ]
