# Generated by Django 5.2.1 on 2025-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_add_dpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('Doctor', models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams'), ('Dr. Brown', 'Dr. Brown'), ('Dr. Jones', 'Dr. Jones')], max_length=20)),
                ('Department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology')], max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Address', models.CharField(max_length=50)),
                
            ],
        ),
        migrations.RemoveField(
            model_name='add',
            name='dprofile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
