# Generated by Django 5.2.1 on 2025-06-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_remove_add_dprofile_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='dprofile',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.CreateModel(
            name='DoctorCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.add')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='charges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.doctorcharges'),
        ),
    ]
