# Generated by Django 3.0.5 on 2025-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_dprofile_user_profile_doctorcharges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='dprofile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AlterField(
            model_name='doctorcharges',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='myapp.Add'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='customerient', max_length=20),
        ),
    ]
