# Generated by Django 3.0.5 on 2025-06-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20250610_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorCharges',
        ),
    ]
