# Generated by Django 5.2.1 on 2025-06-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_consultation_fee_add_department_add_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
