# Generated by Django 5.2.1 on 2025-06-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_add_id_alter_appointment_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='demail',
        ),
    ]
