# Generated by Django 3.0.5 on 2025-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20250611_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='dexperience',
            field=models.IntegerField(),
        ),
    ]
